CREATE TABLE AUTHOR(
A_ID INT PRIMARY KEY,
A_NAME VARCHAR(10),
A_COUNTRY VARCHAR(10),
);
INSERT INTO AUTHOR(A_ID,A_NAME,A_COUNTRY) VALUES(2,'VANSH','INDIA'),(3,'SHANTNU','AMERICA'),(4,'DEEPAK','RUSSIA');
CREATE TABLE BOOK(
A_ID INT ,
BOOK_ID INT PRIMARY KEY,
BOOK_NAME VARCHAR(20),
FOREIGN KEY (A_ID) REFERENCES AUTHOR(A_ID)
);
INSERT INTO BOOK(A_ID,BOOK_ID,BOOK_NAME) VALUES(2,100,'HOLY GRAIL'),(3,101,'A ROOM'),(4,102,'THE ROBBERY');
SELECT * FROM AUTHOR;
SELECT * FROM BOOK;
SELECT
BOOK.BOOK_ID,
BOOK.BOOK_NAME,
AUTHOR.A_NAME,
AUTHOR.A_COUNTRY
FROM
	BOOK
INNER JOIN
	AUTHOR
ON
	BOOK.A_ID = AUTHOR.A_ID;
SELECT
BOOK.BOOK_NAME,
AUTHOR.A_NAME,
AUTHOR.A_COUNTRY
FROM
BOOK
INNER JOIN
AUTHOR
ON
BOOK.A_ID = AUTHOR.A_ID;
